# Usa a imaxe oficial de pgAdmin4
FROM dpage/pgadmin4

# Configura as variábeis de contorno para o administrador
ENV PGADMIN_DEFAULT_EMAIL=admin@example.com
ENV PGADMIN_DEFAULT_PASSWORD=admin

# Expón o porto 80 para pgAdmin
EXPOSE 80
